In [1]:
import os
print(os.getcwd())
os.chdir("../src")
print(os.getcwd())

c:\Users\Nougarède Hugo\Documents\Programming\garmin_data\notebooks
c:\Users\Nougarède Hugo\Documents\Programming\garmin_data\src

In [2]:
from process_data import *
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
raw_data = fetch_data(10000)

activities, zones = process_data(raw_data)

In [4]:
activities.head(10)

,activityId,activity_date,activity_time,distance_km,duration,elevationGain,elevationLoss,averageSpeed,maxSpeed,ownerId,averageHR,maxHR,activityType,aerobicTrainingEffect,anaerobicTrainingEffect,deviceId,locationName,moderateIntensityMinutes,vigorousIntensityMinutes
0,21380637839,2025-12-29,08:58:39,24.21,3600.39,NaN,NaN,24.21,7.68,121637100,132.0,150.0,indoor_cycling,3.2,0.0,3466268921,NaN,NaN,NaN
1,21291812121,2025-12-18,18:22:27,15.97,2339.98,NaN,NaN,24.57,8.16,121637100,152.0,182.0,indoor_cycling,5.0,0.0,3466268921,NaN,13.0,23.0
2,21268909490,2025-12-16,06:10:57,11.49,1800.41,NaN,NaN,22.99,7.02,121637100,123.0,136.0,indoor_cycling,2.6,0.0,3466268921,NaN,28.0,0.0
3,21260385723,2025-12-15,06:18:20,23.63,3600.42,NaN,NaN,23.62,8.05,121637100,120.0,133.0,indoor_cycling,3.3,0.0,3466268921,NaN,53.0,1.0
4,21169670049,2025-12-04,18:21:30,25.42,3603.52,NaN,NaN,25.39,8.70,121637100,129.0,140.0,indoor_cycling,2.8,0.0,3466268921,NaN,NaN,NaN
5,21151221637,2025-12-02,18:09:35,20.90,3360.81,NaN,NaN,22.39,7.82,121637100,151.0,178.0,indoor_cycling,4.1,0.0,3466268921,NaN,24.0,30.0
6,21104459734,2025-11-27,12:05:47,22.11,3600.50,NaN,NaN,22.11,7.12,121637100,125.0,138.0,indoor_cycling,2.7,0.0,3466268921,NaN,NaN,NaN
7,21061358477,2025-11-22,15:35:28,21.03,3493.04,NaN,NaN,21.68,7.08,121637100,132.0,146.0,indoor_cycling,2.3,0.0,3466268921,NaN,53.0,1.0
8,21048546615,2025-11-21,06:41:21,25.10,3604.50,NaN,NaN,25.07,9.43,121637100,145.0,170.0,indoor_cycling,3.9,0.0,3466268921,NaN,NaN,NaN
9,21011203509,2025-11-17,06:27:56,23.01,3601.42,NaN,NaN,23.00,7.18,121637100,125.0,139.0,indoor_cycling,2.8,0.0,3466268921,NaN,46.0,11.0

In [7]:
zones.sort_values(by=["activityId", "zone"])

zones[zones["activityId"] == 21380637839]

      activityId  zone  time_second
0    21380637839     1       66.000
120  21380637839     2     1570.895
240  21380637839     3     1767.308
360  21380637839     4        0.000
480  21380637839     5        0.000

In [8]:
raw_data.head()

,activityId,activityName,startTimeLocal,startTimeGMT,activityType,eventType,distance,duration,elapsedDuration,movingDuration,averageSpeed,maxSpeed,hasPolyline,hasImages,ownerId,ownerDisplayName,ownerFullName,ownerProfileImageUrlSmall,ownerProfileImageUrlMedium,ownerProfileImageUrlLarge,calories,bmrCalories,averageHR,maxHR,averageBikingCadenceInRevPerMinute,maxBikingCadenceInRevPerMinute,userRoles,privacy,userPro,hasVideo,timeZoneId,beginTimestamp,sportTypeId,avgPower,maxPower,aerobicTrainingEffect,anaerobicTrainingEffect,strokes,normPower,max20MinPower,trainingStressScore,intensityFactor,vO2MaxValue,deviceId,minTemperature,maxTemperature,summarizedDiveInfo,manufacturer,lapCount,waterEstimated,maxAvgPower_1,maxAvgPower_2,maxAvgPower_5,maxAvgPower_10,maxAvgPower_20,maxAvgPower_30,maxAvgPower_60,maxAvgPower_120,maxAvgPower_300,maxAvgPower_600,maxAvgPower_1200,maxAvgPower_1800,maxAvgPower_3600,excludeFromPowerCurveReports,minRespirationRate,maxRespirationRate,avgRespirationRate,trainingEffectLabel,activityTrainingLoad,minActivityLapDuration,aerobicTrainingEffectMessage,anaerobicTrainingEffectMessage,splitSummaries,hasSplits,hasHeatMap,hrTimeInZone_1,hrTimeInZone_2,hrTimeInZone_3,hrTimeInZone_4,hrTimeInZone_5,powerTimeInZone_1,powerTimeInZone_2,powerTimeInZone_3,powerTimeInZone_4,powerTimeInZone_5,powerTimeInZone_6,powerTimeInZone_7,endTimeGMT,qualifyingDive,favorite,purposeful,manualActivity,decoDive,elevationCorrected,atpActivity,autoCalcCalories,pr,parent,moderateIntensityMinutes,vigorousIntensityMinutes,workoutId,elevationGain,elevationLoss,startLatitude,startLongitude,minElevation,maxElevation,maxVerticalSpeed,locationName,endLatitude,endLongitude,caloriesConsumed,waterConsumed,courseId,fastestSplit_40000,avgVerticalSpeed,maxFtp
0,21380637839,Indoor Cycling,2025-12-29 08:58:39,2025-12-29 07:58:39,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",24211.320312,3600.385010,3930.446045,3600.385010,6.725,7.679,False,False,121637100,c25b38d9-6c53-4c5c-a2c5-20016b6e6978,Hugo Nougarede,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,568.0,103.0,132.0,150.0,73.0,87.0,"[SCOPE_GOLF_API_READ, SCOPE_DI_OAUTH_2_CREATE_...","{'typeId': 2, 'typeKey': 'private'}",False,False,124,1766995119000,2,129.0,244.0,3.2,0.0,4384.0,129.0,130.497500,34.400002,0.589,35.0,3466268921,20.0,22.0,{'summarizedDiveGases': []},GARMIN,1,431.0,244.0,233.0,201.0,169.0,149.0,143.0,136.0,133.0,131.0,131.0,130.0,130.0,124.0,False,14.43,34.360001,22.799999,AEROBIC_BASE,47.903915,3600.385010,IMPROVING_AEROBIC_BASE_8,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 0, 'duration': 0.0, 'splitType...",False,False,66.000,1570.895,1767.308,0.000,0.000,277.083,3312.305,4.998,4.999,1.000,0.000,0.0,2025-12-29 09:04:09,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21291812121,Indoor Cycling,2025-12-18 18:22:27,2025-12-18 17:22:27,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",15969.620117,2339.978027,2384.979004,2283.394001,6.825,8.164,False,False,121637100,c25b38d9-6c53-4c5c-a2c5-20016b6e6978,Hugo Nougarede,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,484.0,67.0,152.0,182.0,75.0,97.0,"[SCOPE_GOLF_API_READ, SCOPE_DI_OAUTH_2_CREATE_...","{'typeId': 2, 'typeKey': 'private'}",False,False,124,1766078547000,2,178.0,273.0,5.0,0.0,2897.0,199.0,197.361667,53.200001,0.910,37.0,3466268921,21.0,23.0,{'summarizedDiveGases': []},GARMIN,5,414.0,273.0,271.0,262.0,259.0,257.0,256.0,255.0,240.0,237.0,236.0,197.0,191.0,NaN,False,19.01,50.020000,30.740000,VO2MAX,144.213745,6.842000,OVERREACHING_17,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 0, 'duration': 0.0, 'splitType...",False,False,80.999,460.882,585.823,576.177,628.001,213.373,913.078,114.669,214.990,872.009,9.999,0.0,2025-12-18 18:02:11,False,False,False,False,False,False,False,False,False,False,13.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21268909490,Indoor Cycling,2025-12-16 06:10:57,2025-12-16 05:10:57,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",11494.799805,1800.411987,1800.411987,1799.000000,6.385,7.017,False,False,121637100,c25b38d9-6c53-4c5c-a2c5-20016b6e6978,Hugo Nougarede,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,282.0,52.0,123.0,136.0,69.0,78.0,"[SCOPE_GOLF_API_READ, SCOPE_DI_OAUTH_2_CREATE_...","{'typeId': 2, 'typeKey': 'private'}",False,False,124,1765861857000,2,128.0,162.0,2.6,0.0,2076.0,129.0,130.113333,17.000000,0.587,NaN,3466268921,20.0,20.0,{'summarizedDiveGases': []},GARMIN,1,201.0,162.0,159.0,146.0,138.0,134.0,132.0,131.0,131.0,130.0,130.0,130.0,128.0,NaN,False,15.53,22.660000,18.930000,AEROBIC_BASE,27.733063,1800.411987,MAINTAINING_AEROBIC_BASE_7,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 0, 'duration': 0.0, 'splitType...",False,False,109.998,1636.999,22.000,0.000,0.000,207.415,1592.997,0.000,0.000,0.000,0.000,0.0,2025-12-16 05:40:57,False,False,False,False,False,False,False,False,False,False,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21260385723,Indoor Cycling,2025-12-15 06:18:20,2025-12-15 05:18:20,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",23625.630859,3600.418945,3600.418945,3599.000000,6.562,8.052,False,False,121637100,c25b38d9-6c53-4c5c-a2c5-20016b6e6978,Hugo Nougarede,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,584.0,103.0,120.0,133.0,71.0,118.0,"[SCOPE_GOLF_API_READ, SCOPE_DI_OAUTH_2_CREATE_...","{'typeId': 2, 'typeKey': 'private'}",False,False,124,1765775900000,2,134.0,201.0,3.3,0.0,4275.0,134.0,135.986667,37.099998,0.611,NaN,3466268921,20.0,21.0,{'summarizedDiveGases': []},GARMIN,1,420.0,201.0,193.0,168.0,145.0,139.0,138.0,138.0,137.0,137.0,136.0,136.0,136.0,134.0,False,13.54,28.870001,20.230000,AEROBIC_BASE,53.884399,3600.418945,IMPROVING_AEROBIC_BASE_8,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 0, 'duration': 0.0, 'splitType...",False,False,576.002,3006.983,1.000,0.000,0.000,140.433,3455.986,3.000,1.000,0.000,0.000,0.0,2025-12-15 06:18:20,False,False,False,False,False,False,False,False,False,False,53.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21169670049,Indoor Cycling,2025-12-04 18:21:30,2025-12-04 17:21:30,"{'typeId': 25, 'typeKey': 'indoor_cycling', 'p...","{'typeId': 9, 'typeKey': 'uncategorized', 'sor...",25415.720703,3603.523926,3603.523926,3603.523926,7.053,8.696,False,False,121637100,c25b38d9-6c53-4c5c-a2c5-20016b6e6978,Hugo Nougarede,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,https://s3.amazonaws.com/garmin-connect-prod/p...,569.0,104.0,129.0,140.0,76.0,105.0,"[SCOPE_GOLF_API_READ, SCOPE_DI_OAUTH_2_CREATE_...","{'typeId': 2, 'typeKey': 'private'}",False,False,124,1764868890000,2,129.0,250.0,2.8,0.0,4609.0,129.0,130.415000,34.700001,0.591,36.0,3466268921,21.0,21.0,{'summarizedDiveGases': []},GARMIN,1,409.0,250.0,248.0,216.0,172.0,137.0,135.0,132.0,131.0,131.0,131.0,130.0,130.0,129.0,False,15.10,28.170000,21.330000,AEROBIC_BASE,45.008881,3603.523926,MAINTAINING_AEROBIC_BASE_7,NO_ANAEROBIC_BENEFIT_0,"[{'noOfSplits': 0, 'duration': 0.0, 'splitType...",False,False,46.999,2763.373,783.997,0.000,0.000,252.525,3337.997,10.002,0.000,3.000,0.000,0.0,2025-12-04 18:21:33,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
activity_dict = raw_data.loc[raw_data["activityId"]
                             == 21380637839, "activityType"].iloc[0]
print(activity_dict)

{'typeId': 25, 'typeKey': 'indoor_cycling', 'parentTypeId': 2, 'isHidden': False, 'restricted': False, 'trimmable': True}

In [13]:
activity_dict = df.loc[df["activityId"] == 19897077988, "activityType"].iloc[0]
print(activity_dict)

{'typeId': 10, 'typeKey': 'road_biking', 'parentTypeId': 2, 'isHidden': False, 'restricted': False, 'trimmable': True}

In [ ]:
cols_to_keep = [
    "activityId",
    "startTimeLocal",
    "distance",
    "duration",
    "elevationGain",
    "elevationLoss",
    "averageSpeed",
    "maxSpeed",
    "ownerId",
    "averageHR",
    "maxHR",
    "sportTypeId",
    "activityType",
    "aerobicTrainingEffect",
    "anaerobicTrainingEffect",
    "deviceId",
    "locationName",
    "moderateIntensityMinutes",
    "vigorousIntensityMinutes",
    "hrTimeInZone_1",
    "hrTimeInZone_2",
    "hrTimeInZone_3",
    "hrTimeInZone_4",
    "hrTimeInZone_5"
]

# Keep only relevant columns and make a copy to avoid warnings
df = raw_data[cols_to_keep].copy()

In [17]:
df["activityType"] = df["activityType"].apply(lambda x: x.get("typeKey"))

In [19]:
df.head(10)

,activityId,startTimeLocal,distance,duration,elevationGain,elevationLoss,averageSpeed,maxSpeed,ownerId,averageHR,maxHR,sportTypeId,activityType,aerobicTrainingEffect,anaerobicTrainingEffect,deviceId,locationName,moderateIntensityMinutes,vigorousIntensityMinutes,hrTimeInZone_1,hrTimeInZone_2,hrTimeInZone_3,hrTimeInZone_4,hrTimeInZone_5
0,20344625506,2025-09-10 18:44:51,19898.310547,3054.323975,NaN,NaN,6.515,8.659000,121637100,127.0,141.0,2,indoor_cycling,3.0,0.0,3466268921,NaN,27.0,21.0,44.539,2528.783,481.002,0.000,0.000
1,20306106504,2025-09-07 09:13:33,11026.290039,2680.186035,NaN,NaN,4.114,10.861000,121637100,125.0,140.0,2,indoor_cycling,2.1,0.0,3466268921,NaN,33.0,9.0,239.569,2260.018,179.998,0.000,0.000
2,20297420274,2025-09-06 09:31:20,524.210022,155.518997,NaN,NaN,3.371,4.787000,121637100,NaN,NaN,2,indoor_cycling,0.0,0.0,3466268921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20294955309,2025-09-06 08:42:55,811.099976,259.806000,NaN,NaN,3.122,6.559000,121637100,NaN,NaN,2,indoor_cycling,0.0,0.0,3466268921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20294903726,2025-09-06 08:32:20,552.270020,224.487000,NaN,NaN,2.460,3.984000,121637100,NaN,NaN,2,indoor_cycling,0.0,0.0,3466268921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20185650353,2025-08-26 17:19:33,38382.351562,5239.231934,376.0,370.0,7.326,16.934999,121637100,150.0,172.0,2,road_biking,4.3,2.6,3466268921,Lavigny,10.0,72.0,45.997,440.225,2135.007,2596.994,19.999
6,20165465242,2025-08-24 18:54:06,15991.820312,2893.075928,265.0,260.0,5.528,15.330000,121637100,145.0,174.0,2,road_biking,3.6,2.1,3466268921,Lavigny,4.0,36.0,230.074,460.995,905.003,1208.999,88.001
7,19973290005,2025-08-06 18:19:40,38586.699219,5980.957031,383.0,380.0,6.452,15.666000,121637100,137.0,161.0,2,road_biking,3.4,0.7,3466268921,Lavigny,19.0,68.0,230.088,1637.566,3672.999,439.999,0.000
8,19973255011,2025-08-03 10:14:54,14273.379883,3465.477051,231.0,227.0,4.119,11.421000,121637100,123.0,168.0,2,road_biking,2.5,2.0,3466268921,Lavigny,24.0,27.0,1009.465,1467.014,642.999,250.999,0.000
9,19897077988,2025-07-30 16:30:19,31935.050781,5088.128906,379.0,378.0,6.276,15.722000,121637100,139.0,158.0,2,road_biking,3.4,0.3,3466268921,Lavigny,NaN,NaN,144.997,1376.131,2963.997,602.997,0.000

In [ ]:
zones = raw_data[["activityId", "hrTimeInZone_1", "hrTimeInZone_2", "hrTimeInZone_3",
                  "hrTimeInZone_4", "hrTimeInZone_5"]]

In [26]:
# Pivot from wide to long format
zones_long = zones.melt(
    id_vars=["activityId"],               # columns to keep as identifiers
    value_vars=["hrTimeInZone_1", "hrTimeInZone_2", "hrTimeInZone_3",
                "hrTimeInZone_4", "hrTimeInZone_5"],  # columns to unpivot
    var_name="zone",                      # name for the new 'zone' column
    value_name="time_second"              # name for the values
)

# Convert zone names from 'hrTimeInZone_1' → 1
zones_long["zone"] = zones_long["zone"].str.extract("(\d+)").astype(int)

zones_long["time_second"] = zones_long["time_second"].fillna(0)

In [27]:
zones_long

      activityId  zone  time_second
0    20344625506     1       44.539
1    20306106504     1      239.569
2    20297420274     1        0.000
3    20294955309     1        0.000
4    20294903726     1        0.000
5    20185650353     1       45.997
6    20165465242     1      230.074
7    19973290005     1      230.088
8    19973255011     1     1009.465
9    19897077988     1      144.997
10   19843189834     1       64.575
11   19822484112     1      221.839
12   19793554374     1     1079.258
13   19792418758     1        0.000
14   19760403834     1      145.826
15   19753462594     1      104.745
16   19753454549     1     1729.005
17   19573490633     1     2009.823
18   19543625199     1       21.001
19   19499486485     1       63.003
20   19472696241     1      202.998
21   19402085414     1        8.016
22   19396584710     1       54.000
23   19377385523     1     1499.326
24   19298725893     1     2871.346
25   19260847795     1       11.000
26   19256436907     1      171.807
27   19212668586     1        4.132
28   19209564037     1        0.000
29   19150342006     1      895.984
30   19148780071     1     1347.763
31   19003943981     1        0.000
32   19003940610     1        0.000
33   16732143065     1        0.000
34   16601676794     1        0.000
35   16594025437     1        0.000
36   16588254197     1        0.000
37   16574727884     1        0.000
38   16557185859     1        0.000
39   16557172851     1        0.000
40   16479526857     1        0.000
41   16461522563     1        0.000
42   16386167531     1        0.000
43   16354407514     1        0.000
44   16342523727     1        0.000
45   16319165641     1        0.000
46   16301677581     1        0.000
47   16139649786     1        0.000
48   16123495283     1        0.000
49   16086736827     1        0.000
50   20344625506     2     2528.783
51   20306106504     2     2260.018
52   20297420274     2        0.000
53   20294955309     2        0.000
54   20294903726     2        0.000
55   20185650353     2      440.225
56   20165465242     2      460.995
57   19973290005     2     1637.566
58   19973255011     2     1467.014
59   19897077988     2     1376.131
60   19843189834     2      803.997
61   19822484112     2      879.994
62   19793554374     2     2301.992
63   19792418758     2        0.000
64   19760403834     2      535.411
65   19753462594     2      945.000
66   19753454549     2     1893.026
67   19573490633     2     1749.002
68   19543625199     2      514.915
69   19499486485     2     1326.840
70   19472696241     2      864.998
71   19402085414     2      356.652
72   19396584710     2      458.914
73   19377385523     2     2442.001
74   19298725893     2     3117.726
75   19260847795     2      512.998
76   19256436907     2      364.997
77   19212668586     2      332.000
78   19209564037     2      248.659
79   19150342006     2     2904.985
80   19148780071     2     2754.003
81   19003943981     2        0.000
82   19003940610     2        0.000
83   16732143065     2        0.000
84   16601676794     2        0.000
85   16594025437     2        0.000
86   16588254197     2        0.000
87   16574727884     2        0.000
88   16557185859     2        0.000
89   16557172851     2        0.000
90   16479526857     2        0.000
91   16461522563     2        0.000
92   16386167531     2        0.000
93   16354407514     2        0.000
94   16342523727     2        0.000
95   16319165641     2        0.000
96   16301677581     2        0.000
97   16139649786     2        0.000
98   16123495283     2        0.000
99   16086736827     2        0.000
100  20344625506     3      481.002
101  20306106504     3      179.998
102  20297420274     3        0.000
103  20294955309     3        0.000
104  20294903726     3        0.000
105  20185650353     3     2135.007
106  20165465242     3      905.003
107  19973290005     3     3672.999
108  19973255011     3      642.999
109  19897077988     3     2963.997
110  19843189834     3     2994.997
111  19822484112     3     2928.003
112  19793554374     3     1135.007
113  19792418758     3        0.000
114  19760403834     3     1913.992
115  19753462594     3     2097.002
116  19753454549     3     1540.991
117  19573490633     3      119.999
118  19543625199     3     1919.948
119  19499486485     3     3352.599
120  19472696241     3     1442.266
121  19402085414     3     1384.354
122  19396584710     3     1600.236
123  19377385523     3     1102.005
124  19298725893     3     1404.002
125  19260847795     3     1749.744
126  19256436907     3      958.859
127  19212668586     3     1398.006
128  19209564037     3      973.850
129  19150342006     3     2537.990
130  19148780071     3     1247.004
131  19003943981     3        0.000
132  19003940610     3        0.000
133  16732143065     3        0.000
134  16601676794     3        0.000
135  16594025437     3        0.000
136  16588254197     3        0.000
137  16574727884     3        0.000
138  16557185859     3        0.000
139  16557172851     3        0.000
140  16479526857     3        0.000
141  16461522563     3        0.000
142  16386167531     3        0.000
143  16354407514     3        0.000
144  16342523727     3        0.000
145  16319165641     3        0.000
146  16301677581     3        0.000
147  16139649786     3        0.000
148  16123495283     3        0.000
149  16086736827     3        0.000
150  20344625506     4        0.000
151  20306106504     4        0.000
152  20297420274     4        0.000
153  20294955309     4        0.000
154  20294903726     4        0.000
155  20185650353     4     2596.994
156  20165465242     4     1208.999
157  19973290005     4      439.999
158  19973255011     4      250.999
159  19897077988     4      602.997
160  19843189834     4      618.001
161  19822484112     4     1857.000
162  19793554374     4      247.999
163  19792418758     4        0.000
164  19760403834     4      717.005
165  19753462594     4     2554.998
166  19753454549     4      323.004
167  19573490633     4        0.000
168  19543625199     4     2960.993
169  19499486485     4     4473.400
170  19472696241     4     3614.733
171  19402085414     4     2075.997
172  19396584710     4     1274.150
173  19377385523     4      219.999
174  19298725893     4      118.925
175  19260847795     4     1612.004
176  19256436907     4     1891.000
177  19212668586     4     2198.006
178  19209564037     4     1994.005
179  19150342006     4      591.004
180  19148780071     4      186.998
181  19003943981     4        0.000
182  19003940610     4        0.000
183  16732143065     4        0.000
184  16601676794     4        0.000
185  16594025437     4        0.000
186  16588254197     4        0.000
187  16574727884     4        0.000
188  16557185859     4        0.000
189  16557172851     4        0.000
190  16479526857     4        0.000
191  16461522563     4        0.000
192  16386167531     4        0.000
193  16354407514     4        0.000
194  16342523727     4        0.000
195  16319165641     4        0.000
196  16301677581     4        0.000
197  16139649786     4        0.000
198  16123495283     4        0.000
199  16086736827     4        0.000
200  20344625506     5        0.000
201  20306106504     5        0.000
202  20297420274     5        0.000
203  20294955309     5        0.000
204  20294903726     5        0.000
205  20185650353     5       19.999
206  20165465242     5       88.001
207  19973290005     5        0.000
208  19973255011     5        0.000
209  19897077988     5        0.000
210  19843189834     5        0.000
211  19822484112     5        0.000
212  19793554374     5        0.000
213  19792418758     5        0.000
214  19760403834     5        0.000
215  19753462594     5        0.000
216  19753454549     5        0.000
217  19573490633     5        0.000
218  19543625199     5       52.002
219  19499486485     5       34.999
220  19472696241     5       11.000
221  19402085414     5       35.000
222  19396584710     5       79.001
223  19377385523     5        0.000
224  19298725893     5       24.998
225  19260847795     5        0.000
226  19256436907     5      143.001
227  19212668586     5       43.998
228  19209564037     5      174.997
229  19150342006     5        0.000
230  19148780071     5        0.000
231  19003943981     5        0.000
232  19003940610     5        0.000
233  16732143065     5        0.000
234  16601676794     5        0.000
235  16594025437     5        0.000
236  16588254197     5        0.000
237  16574727884     5        0.000
238  16557185859     5        0.000
239  16557172851     5        0.000
240  16479526857     5        0.000
241  16461522563     5        0.000
242  16386167531     5        0.000
243  16354407514     5        0.000
244  16342523727     5        0.000
245  16319165641     5        0.000
246  16301677581     5        0.000
247  16139649786     5        0.000
248  16123495283     5        0.000
249  16086736827     5        0.000