In [37]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_csv('../csv/Lausanne_Triathlon_2026/main.csv')

# 🔧 FIX: convert to datetime
df["activity_date"] = pd.to_datetime(df["activity_date"])

start = pd.to_datetime('2026-04-27')
end = pd.to_datetime('2026-05-01')

df_small = df[df['activity_date'].between(start, end)]

df_small

,activityId,activity_date,activity_time,distance_km,duration,elevationGain,elevationLoss,averageSpeed,maxSpeed,ownerId,averageHR,maxHR,activityType,aerobicTrainingEffect,anaerobicTrainingEffect,deviceId,locationName,moderateIntensityMinutes,vigorousIntensityMinutes,zone1,zone2,zone3,zone4,zone5
71,22715425183,2026-04-30,16:48:43,34.93,4716.24,338.0,330.0,26.67,18.02,121637100,153.0,175.0,road_biking,4.1,2.2,3466268921,Lavigny,26.0,54.0,34.998,326.584,1530.85,2753.722,67.999
72,22724914214,2026-05-01,09:28:16,83.36,14516.99,1200.0,1194.0,20.67,15.93,121637100,147.0,178.0,road_biking,5.0,2.2,3466268921,Lavigny,109.0,112.0,991.361,2035.989,4232.97,6910.962,323.000

In [31]:
df.columns

Index(['activityId', 'activity_date', 'activity_time', 'distance_km',
       'duration', 'elevationGain', 'elevationLoss', 'averageSpeed',
       'maxSpeed', 'ownerId', 'averageHR', 'maxHR', 'activityType',
       'aerobicTrainingEffect', 'anaerobicTrainingEffect', 'deviceId',
       'locationName', 'moderateIntensityMinutes', 'vigorousIntensityMinutes',
       'zone1', 'zone2', 'zone3', 'zone4', 'zone5'],
      dtype='str')

In [35]:
df["activityType"].unique()

<ArrowStringArray>
[                 'hiking',            'lap_swimming',
                 'running',          'indoor_cycling',
 'cross_country_skiing_ws',             'road_biking']
Length: 6, dtype: str

In [39]:
df_run = df[df['activityType'] == 'running']
df_run.head()

,activityId,activity_date,activity_time,distance_km,duration,elevationGain,elevationLoss,averageSpeed,maxSpeed,ownerId,averageHR,maxHR,activityType,aerobicTrainingEffect,anaerobicTrainingEffect,deviceId,locationName,moderateIntensityMinutes,vigorousIntensityMinutes,zone1,zone2,zone3,zone4,zone5
2,21457322519,2026-01-06,06:34:53,4.29,2123.32,21.0,21.0,7.28,2.55,121637100,145.0,163.0,running,3.4,0.0,3614308067,Lavigny,22.0,13.0,249.370,1044.989,20855.186,1206.205,0.0
8,21548937002,2026-01-14,18:34:53,5.21,2700.31,19.0,18.0,6.95,2.58,121637100,148.0,161.0,running,2.9,0.0,3614308067,Lavigny,35.0,10.0,137.480,1136.056,19791.824,536.392,0.0
9,21564721954,2026-01-16,12:08:58,7.15,3600.31,96.0,98.0,7.15,2.95,121637100,152.0,170.0,running,3.6,0.0,3614308067,Lavigny,20.0,39.0,144.000,584.064,21703.272,6252.816,0.0
12,21620736499,2026-01-21,12:12:03,5.61,2700.52,18.0,17.0,7.48,2.83,121637100,149.0,162.0,running,3.1,0.0,3614308067,Lavigny,9.0,33.0,72.006,821.988,12983.790,2259.132,0.0
14,21639344583,2026-01-23,12:09:22,5.57,2700.35,20.0,23.0,7.43,3.34,121637100,151.0,161.0,running,2.9,0.0,3614308067,Lavigny,11.0,31.0,114.006,431.994,13319.586,2173.362,0.0

In [22]:
from garminconnect import Garmin
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent / "src"))

from config import EMAIL, PASSWORD

# Create client
client = Garmin(EMAIL, PASSWORD)

# 🔑 IMPORTANT: login first
client.login()

activity_id = 22715425183  

details = client.get_activity_details(activity_id)

mobile+cffi returned 429: Mobile login returned 429 — IP rate limited by Garmin
mobile+requests returned 429: Mobile login returned 429 — IP rate limited by Garmin

dict_keys(['activityId', 'measurementCount', 'metricsCount', 'totalMetricsCount', 'metricDescriptors', 'activityDetailMetrics', 'geoPolylineDTO', 'heartRateDTOs', 'pendingData', 'detailsAvailable'])

In [23]:
print(details.keys())

dict_keys(['activityId', 'measurementCount', 'metricsCount', 'totalMetricsCount', 'metricDescriptors', 'activityDetailMetrics', 'geoPolylineDTO', 'heartRateDTOs', 'pendingData', 'detailsAvailable'])

In [28]:
details["metricDescriptors"]

[{'metricsIndex': 0,
  'key': 'directPotentialStamina',
  'unit': {'id': 6, 'key': 'dimensionless', 'factor': 1.0}},
 {'metricsIndex': 1,
  'key': 'directLongitude',
  'unit': {'id': 60, 'key': 'dd', 'factor': 1.0}},
 {'metricsIndex': 2,
  'key': 'directLatitude',
  'unit': {'id': 60, 'key': 'dd', 'factor': 1.0}},
 {'metricsIndex': 3,
  'key': 'sumDuration',
  'unit': {'id': 40, 'key': 'second', 'factor': 1000.0}},
 {'metricsIndex': 4,
  'key': 'directSpeed',
  'unit': {'id': 20, 'key': 'mps', 'factor': 0.1}},
 {'metricsIndex': 5,
  'key': 'directElevation',
  'unit': {'id': 1, 'key': 'meter', 'factor': 100.0}},
 {'metricsIndex': 6,
  'key': 'directAirTemperature',
  'unit': {'id': 227, 'key': 'celcius', 'factor': 1.0}},
 {'metricsIndex': 7,
  'key': 'sumDistance',
  'unit': {'id': 1, 'key': 'meter', 'factor': 100.0}},
 {'metricsIndex': 8,
  'key': 'directHeartRate',
  'unit': {'id': 100, 'key': 'bpm', 'factor': 1.0}},
 {'metricsIndex': 9,
  'key': 'sumElapsedDuration',
  'unit': {'id': 40, 'key': 'second', 'factor': 1000.0}},
 {'metricsIndex': 10,
  'key': 'directTimestamp',
  'unit': {'id': 120, 'key': 'gmt', 'factor': 0.0}},
 {'metricsIndex': 11,
  'key': 'directAvailableStamina',
  'unit': {'id': 6, 'key': 'dimensionless', 'factor': 1.0}},
 {'metricsIndex': 12,
  'key': 'sumMovingDuration',
  'unit': {'id': 40, 'key': 'second', 'factor': 1000.0}},
 {'metricsIndex': 13,
  'key': 'directVerticalSpeed',
  'unit': {'id': 20, 'key': 'mps', 'factor': 0.1}},
 {'metricsIndex': 14,
  'key': 'directRespirationRate',
  'unit': {'id': 513, 'key': 'breathsPerMinute', 'factor': 1.0}}]

In [29]:
details["activityDetailMetrics"]

[{'metrics': [100.0,
   6.405751900747418,
   46.50126155465841,
   0.0,
   0.0,
   519.7999877929688,
   24.0,
   0.0,
   106.0,
   0.0,
   1777560523000.0,
   100.0,
   0.0,
   None,
   None]},
 {'metrics': [100.0,
   6.405759947374463,
   46.50126088410616,
   1.0,
   1.0169999599456787,
   519.7999877929688,
   24.0,
   0.0,
   106.0,
   1.0,
   1777560524000.0,
   100.0,
   1.0,
   0.0,
   None]},
 {'metrics': [100.0,
   6.405781405046582,
   46.50122534483671,
   3.0,
   1.7259999513626099,
   520.0,
   24.0,
   4.340000152587891,
   106.0,
   3.0,
   1777560526000.0,
   100.0,
   3.0,
   0.20000000298023224,
   None]},
 {'metrics': [100.0,
   6.405812501907349,
   46.501166839152575,
   6.0,
   2.4539999961853027,
   519.7999877929688,
   24.0,
   11.5600004196167,
   107.0,
   6.0,
   1777560529000.0,
   100.0,
   6.0,
   0.0,
   None]},
 {'metrics': [100.0,
   6.4058249071240425,
   46.50108846835792,
   9.0,
   3.3959999084472656,
   519.7999877929688,
   24.0,
   20.440000534057617,
   106.0,
   9.0,
   1777560532000.0,
   100.0,
   9.0,
   0.0,
   25.010000228881836]},
 {'metrics': [100.0,
   6.4058151841163635,
   46.50098788551986,
   12.0,
   3.6579999923706055,
   519.7999877929688,
   24.0,
   31.34000015258789,
   107.0,
   12.0,
   1777560535000.0,
   100.0,
   12.0,
   0.0,
   25.010000228881836]},
 {'metrics': [100.0,
   6.40585164539516,
   46.500897193327546,
   15.0,
   3.3310000896453857,
   519.7999877929688,
   24.0,
   41.72999954223633,
   107.0,
   15.0,
   1777560538000.0,
   100.0,
   15.0,
   0.0,
   26.1200008392334]},
 {'metrics': [100.0,
   6.40588684938848,
   46.50082552805543,
   18.0,
   1.930999994277954,
   520.4000244140625,
   24.0,
   50.68000030517578,
   107.0,
   18.0,
   1777560541000.0,
   100.0,
   18.0,
   0.4000000059604645,
   25.68000030517578]},
 {'metrics': [100.0,
   6.405858434736729,
   46.50077808648348,
   21.0,
   2.9860000610351562,
   520.7999877929688,
   24.0,
   55.880001068115234,
   104.0,
   21.0,
   1777560544000.0,
   100.0,
   21.0,
   0.0,
   25.68000030517578]},
 {'metrics': [100.0,
   6.405827421694994,
   46.500765765085816,
   22.0,
   3.3310000896453857,
   520.7999877929688,
   24.0,
   58.529998779296875,
   103.0,
   22.0,
   1777560545000.0,
   100.0,
   22.0,
   0.0,
   25.0]},
 {'metrics': [100.0,
   6.405739076435566,
   46.50073676370084,
   24.0,
   3.9660000801086426,
   520.2000122070312,
   24.0,
   66.08999633789062,
   107.0,
   24.0,
   1777560547000.0,
   100.0,
   24.0,
   -0.20000000298023224,
   25.0]},
 {'metrics': [100.0,
   6.405578143894672,
   46.50069896131754,
   27.0,
   4.656000137329102,
   519.5999755859375,
   24.0,
   79.2699966430664,
   112.0,
   27.0,
   1777560550000.0,
   100.0,
   27.0,
   -0.20000000298023224,
   25.0]},
 {'metrics': [100.0,
   6.405394077301025,
   46.50065847672522,
   30.0,
   4.992000102996826,
   519.5999755859375,
   24.0,
   93.9800033569336,
   116.0,
   30.0,
   1777560553000.0,
   100.0,
   30.0,
   0.0,
   23.75]},
 {'metrics': [100.0,
   6.405214620754123,
   46.50063492357731,
   33.0,
   4.580999851226807,
   519.5999755859375,
   24.0,
   108.11000061035156,
   117.0,
   33.0,
   1777560556000.0,
   100.0,
   33.0,
   0.0,
   22.530000686645508]},
 {'metrics': [100.0,
   6.405159384012222,
   46.50063207373023,
   34.0,
   4.422999858856201,
   519.5999755859375,
   24.0,
   112.47000122070312,
   118.0,
   34.0,
   1777560557000.0,
   100.0,
   34.0,
   0.0,
   22.530000686645508]},
 {'metrics': [100.0,
   6.4050456415861845,
   46.50064481422305,
   36.0,
   4.544000148773193,
   519.4000244140625,
   24.0,
   121.01000213623047,
   118.0,
   36.0,
   1777560559000.0,
   100.0,
   36.0,
   0.0,
   22.530000686645508]},
 {'metrics': [100.0,
   6.404861155897379,
   46.500647915527225,
   39.0,
   4.552999973297119,
   519.4000244140625,
   24.0,
   135.11000061035156,
   118.0,
   39.0,
   1777560562000.0,
   100.0,
   39.0,
   0.0,
   21.709999084472656]},
 {'metrics': [100.0,
   6.40467306599021,
   46.50063844397664,
   42.0,
   4.9079999923706055,
   519.5999755859375,
   24.0,
   149.47999572753906,
   119.0,
   42.0,
   1777560565000.0,
   100.0,
   42.0,
   0.0,
   21.709999084472656]},
 {'metrics': [100.0,
   6.404530489817262,
   46.50073617696762,
   45.0,
   5.076000213623047,
   519.7999877929688,
   24.0,
   164.60000610351562,
   118.0,
   45.0,
   1777560568000.0,
   100.0,
   45.0,
   0.0,
   20.770000457763672]},
 {'metrics': [100.0,
   6.404490675777197,
   46.50086651556194,
   48.0,
   4.964000225067139,
   520.0,
   24.0,
   178.7899932861328,
   119.0,
   48.0,
   1777560571000.0,
   100.0,
   48.0,
   0.20000000298023224,
   20.540000915527344]},
 {'metrics': [100.0,
   6.404487742111087,
   46.500911610201,
   49.0,
   4.823999881744385,
   520.0,
   25.0,
   184.13999938964844,
   120.0,
   49.0,
   1777560572000.0,
   100.0,
   49.0,
   0.0,
   20.540000915527344]},
 {'metrics': [100.0,
   6.4044825453311205,
   46.50099375285208,
   51.0,
   5.011000156402588,
   520.4000244140625,
   25.0,
   193.19000244140625,
   121.0,
   51.0,
   1777560574000.0,
   100.0,
   51.0,
   0.20000000298023224,
   20.540000915527344]},
 {'metrics': [100.0,
   6.4044813718646765,
   46.501122834160924,
   54.0,
   4.208000183105469,
   520.7999877929688,
   25.0,
   207.33999633789062,
   120.0,
   54.0,
   1777560577000.0,
   100.0,
   54.0,
   0.20000000298023224,
   21.56999969482422]},
 {'metrics': [100.0,
   6.404467793181539,
   46.50119969621301,
   57.0,
   1.7359999418258667,
   521.0,
   25.0,
   216.27000427246094,
   118.0,
   57.0,
   1777560580000.0,
   100.0,
   57.0,
   0.0,
   21.56999969482422]},
 {'metrics': [100.0,
   6.404467541724443,
   46.50121696293354,
   58.0,
   1.6610000133514404,
   521.0,
   25.0,
   218.1199951171875,
   117.0,
   58.0,
   1777560581000.0,
   100.0,
   58.0,
   0.0,
   22.25]},
 {'metrics': [100.0,
   6.4045008178800344,
   46.50125266984105,
   60.0,
   3.181999921798706,
   521.0,
   25.0,
   222.33999633789062,
   118.0,
   60.0,
   1777560583000.0,
   100.0,
   60.0,
   0.0,
   22.25]},
 {'metrics': [100.0,
   6.404640879482031,
   46.501298351213336,
   63.0,
   4.385000228881836,
   521.4000244140625,
   25.0,
   234.05999755859375,
   119.0,
   63.0,
   1777560586000.0,
   100.0,
   63.0,
   0.20000000298023224,
   24.68000030517578]},
 {'metrics': [100.0,
   6.404812373220921,
   46.501355515792966,
   66.0,
   4.870999813079834,
   521.7999877929688,
   25.0,
   248.47999572753906,
   120.0,
   66.0,
   1777560589000.0,
   100.0,
   66.0,
   0.20000000298023224,
   24.68000030517578]},
 {'metrics': [100.0,
   6.405001552775502,
   46.501420391723514,
   69.0,
   5.123000144958496,
   522.0,
   25.0,
   264.92999267578125,
   123.0,
   69.0,
   1777560592000.0,
   100.0,
   69.0,
   0.20000000298023224,
   26.290000915527344]},
 {'metrics': [100.0,
   6.405190313234925,
   46.50148308835924,
   72.0,
   5.421000003814697,
   521.7999877929688,
   25.0,
   281.25,
   125.0,
   72.0,
   1777560595000.0,
   100.0,
   72.0,
   0.0,
   25.399999618530273]},
 {'metrics': [100.0,
   6.405392652377486,
   46.501540672034025,
   75.0,
   5.756999969482422,
   521.7999877929688,
   25.0,
   298.1199951171875,
   128.0,
   75.0,
   1777560598000.0,
   100.0,
   75.0,
   0.0,
   25.399999618530273]},
 {'metrics': [99.0,
   6.405603876337409,
   46.501596327871084,
   78.0,
   6.1020002365112305,
   522.0,
   25.0,
   315.19000244140625,
   132.0,
   78.0,
   1777560601000.0,
   99.0,
   78.0,
   0.0,
   24.809999465942383]},
 {'metrics': [99.0,
   6.405842425301671,
   46.50166070088744,
   81.0,
   6.401000022888184,
   521.7999877929688,
   25.0,
   335.0,
   132.0,
   81.0,
   1777560604000.0,
   99.0,
   81.0,
   0.0,
   24.809999465942383]},
 {'metrics': [99.0,
   6.406077202409506,
   46.50174074806273,
   84.0,
   6.77400016784668,
   522.0,
   25.0,
   355.3299865722656,
   131.0,
   84.0,
   1777560607000.0,
   99.0,
   84.0,
   0.0,
   23.6200008392334]},
 {'metrics': [99.0,
   6.406316924840212,
   46.501822639256716,
   87.0,
   7.258999824523926,
   522.0,
   25.0,
   375.739990234375,
   132.0,
   87.0,
   1777560610000.0,
   99.0,
   87.0,
   0.0,
   22.84000015258789]},
 {'metrics': [99.0,
   6.406588414683938,
   46.50191819295287,
   90.0,
   7.605000019073486,
   521.5999755859375,
   25.0,
   398.8900146484375,
   132.0,
   90.0,
   1777560613000.0,
   99.0,
   90.0,
   -0.20000000298023224,
   22.84000015258789]},
 {'metrics': [99.0,
   6.406850600615144,
   46.50201617740095,
   93.0,
   7.72599983215332,
   521.2000122070312,
   25.0,
   421.8399963378906,
   134.0,
   93.0,
   1777560616000.0,
   99.0,
   93.0,
   -0.20000000298023224,
   23.489999771118164]},
 {'metrics': [99.0,
   6.4071230962872505,
   46.502120113000274,
   96.0,
   7.670000076293945,
   520.7999877929688,
   25.0,
   445.8699951171875,
   134.0,
   96.0,
   1777560619000.0,
   99.0,
   96.0,
   -0.20000000298023224,
   23.489999771118164]},
 {'metrics': [99.0,
   6.407388215884566,
   46.50222455151379,
   99.0,
   7.670000076293945,
   520.5999755859375,
   25.0,
   469.3500061035156,
   134.0,
   99.0,
   1777560622000.0,
   99.0,
   99.0,
   0.0,
   24.31999969482422]},
 {'metrics': [99.0,
   6.407643696293235,
   46.502340557053685,
   102.0,
   7.818999767303467,
   520.5999755859375,
   25.0,
   492.7699890136719,
   136.0,
   102.0,
   1777560625000.0,
   99.0,
   102.0,
   0.0,
   25.270000457763672]},
 {'metrics': [99.0,
   6.407889872789383,
   46.50247081182897,
   105.0,
   7.949999809265137,
   520.4000244140625,
   24.0,
   516.5900268554688,
   137.0,
   105.0,
   1777560628000.0,
   99.0,
   105.0,
   0.0,
   25.270000457763672]},
 {'metrics': [99.0,
   6.408129595220089,
   46.50260810740292,
   108.0,
   7.894000053405762,
   520.2000122070312,
   24.0,
   540.6799926757812,
   136.0,
   108.0,
   1777560631000.0,
   99.0,
   108.0,
   -0.20000000298023224,
   26.290000915527344]},
 {'metrics': [99.0,
   6.408356158062816,
   46.50274196639657,
   111.0,
   7.659999847412109,
   520.0,
   24.0,
   563.3400268554688,
   136.0,
   111.0,
   1777560634000.0,
   99.0,
   111.0,
   -0.20000000298023224,
   26.290000915527344]},
 {'metrics': [99.0,
   6.408566711470485,
   46.502886889502406,
   114.0,
   7.446000099182129,
   519.7999877929688,
   24.0,
   586.010009765625,
   136.0,
   114.0,
   1777560637000.0,
   99.0,
   114.0,
   -0.20000000298023224,
   25.399999618530273]},
 {'metrics': [99.0,
   6.4087682124227285,
   46.50302787311375,
   117.0,
   7.2779998779296875,
   519.5999755859375,
   24.0,
   608.030029296875,
   135.0,
   117.0,
   1777560640000.0,
   99.0,
   117.0,
   -0.20000000298023224,
   25.989999771118164]},
 {'metrics': [99.0,
   6.408980609849095,
   46.50316592305899,
   120.0,
   7.2129998207092285,
   519.4000244140625,
   24.0,
   630.5700073242188,
   135.0,
   120.0,
   1777560643000.0,
   99.0,
   120.0,
   0.0,
   25.989999771118164]},
 {'metrics': [99.0,
   6.409197868779302,
   46.503291483968496,
   123.0,
   7.026000022888184,
   519.5999755859375,
   24.0,
   652.4199829101562,
   134.0,
   123.0,
   1777560646000.0,
   99.0,
   123.0,
   0.0,
   25.989999771118164]},
 {'metrics': [99.0,
   6.409397693350911,
   46.50341126136482,
   126.0,
   6.894999980926514,
   519.7999877929688,
   24.0,
   672.6500244140625,
   134.0,
   126.0,
   1777560649000.0,
   99.0,
   126.0,
   0.0,
   25.989999771118164]},
 {'metrics': [99.0,
   6.409600032493472,
   46.50354025885463,
   129.0,
   6.90500020980835,
   520.0,
   24.0,
   693.719970703125,
   137.0,
   129.0,
   1777560652000.0,
   99.0,
   129.0,
   0.0,
   25.200000762939453]},
 {'metrics': [99.0,
   6.409796923398972,
   46.50367118418217,
   132.0,
   6.886000156402588,
   520.2000122070312,
   24.0,
   714.8499755859375,
   139.0,
   132.0,
   1777560655000.0,
   99.0,
   132.0,
   0.20000000298023224,
   25.06999969482422]},
 {'metrics': [99.0,
   6.409995574504137,
   46.5037989243865,
   135.0,
   6.839000225067139,
   520.2000122070312,
   24.0,
   735.5700073242188,
   141.0,
   135.0,
   1777560658000.0,
   99.0,
   135.0,
   0.0,
   25.06999969482422]},
 {'metrics': [99.0,
   6.410191543400288,
   46.50392984971404,
   138.0,
   6.829999923706055,
   520.2000122070312,
   24.0,
   756.5399780273438,
   143.0,
   138.0,
   1777560661000.0,
   99.0,
   138.0,
   0.0,
   26.15999984741211]},
 {'metrics': [99.0,
   6.410387512296438,
   46.50405767373741,
   141.0,
   6.848999977111816,
   520.4000244140625,
   24.0,
   777.25,
   142.0,
   141.0,
   1777560664000.0,
   99.0,
   141.0,
   0.0,
   26.15999984741211]},
 {'metrics': [99.0,
   6.410587420687079,
   46.504182228818536,
   144.0,
   6.867000102996826,
   520.5999755859375,
   24.0,
   797.969970703125,
   142.0,
   144.0,
   1777560667000.0,
   99.0,
   144.0,
   0.0,
   26.100000381469727]},
 {'metrics': [99.0,
   6.410783305764198,
   46.504306280985475,
   147.0,
   6.802000045776367,
   520.7999877929688,
   24.0,
   818.3200073242188,
   142.0,
   147.0,
   1777560670000.0,
   99.0,
   147.0,
   0.20000000298023224,
   26.100000381469727]},
 {'metrics': [99.0,
   6.4109820406883955,
   46.5044326800853,
   150.0,
   6.810999870300293,
   520.7999877929688,
   24.0,
   839.0900268554688,
   142.0,
   150.0,
   1777560673000.0,
   99.0,
   150.0,
   0.0,
   24.8799991607666]},
 {'metrics': [99.0,
   6.411177674308419,
   46.50455581024289,
   153.0,
   6.810999870300293,
   520.7999877929688,
   24.0,
   859.3900146484375,
   143.0,
   153.0,
   1777560676000.0,
   99.0,
   153.0,
   0.0,
   24.459999084472656]},
 {'metrics': [99.0,
   6.411372721195221,
   46.50468313135207,
   156.0,
   6.867000102996826,
   520.7999877929688,
   24.0,
   879.9299926757812,
   143.0,
   156.0,
   1777560679000.0,
   99.0,
   156.0,
   0.0,
   24.459999084472656]},
 {'metrics': [99.0,
   6.4115698635578156,
   46.504813553765416,
   159.0,
   6.745999813079834,
   521.0,
   24.0,
   901.0599975585938,
   143.0,
   159.0,
   1777560682000.0,
   99.0,
   159.0,
   0.0,
   24.969999313354492]},
 {'metrics': [99.0,
   6.411763317883015,
   46.50493483990431,
   162.0,
   6.7179999351501465,
   521.2000122070312,
   24.0,
   921.0499877929688,
   144.0,
   162.0,
   1777560685000.0,
   99.0,
   162.0,
   0.20000000298023224,
   24.969999313354492]},
 {'metrics': [99.0,
   6.411960124969482,
   46.50506157428026,
   165.0,
   6.755000114440918,
   521.2000122070312,
   24.0,
   941.6599731445312,
   144.0,
   165.0,
   1777560688000.0,
   99.0,
   165.0,
   0.0,
   26.09000015258789]},
 {'metrics': [99.0,
   6.412149388343096,
   46.50519032031298,
   168.0,
   6.6529998779296875,
   521.2000122070312,
   24.0,
   962.0900268554688,
   143.0,
   168.0,
   1777560691000.0,
   99.0,
   168.0,
   0.0,
   25.65999984741211]},
 {'metrics': [99.0,
   6.412338986992836,
   46.50531370192766,
   171.0,
   6.625,
   521.4000244140625,
   24.0,
   981.8800048828125,
   143.0,
   171.0,
   1777560694000.0,
   99.0,
   171.0,
   0.0,
   25.65999984741211]},
 {'metrics': [99.0,
   6.412529004737735,
   46.505444794893265,
   174.0,
   6.625,
   521.4000244140625,
   24.0,
   1002.6699829101562,
   144.0,
   174.0,
   1777560697000.0,
   99.0,
   174.0,
   0.0,
   25.770000457763672]},
 {'metrics': [99.0,
   6.412716340273619,
   46.50557396002114,
   177.0,
   6.802000045776367,
   521.4000244140625,
   24.0,
   1023.0599975585938,
   144.0,
   177.0,
   1777560700000.0,
   99.0,
   177.0,
   0.0,
   26.6299991607666]},
 {'metrics': [99.0,
   6.412912057712674,
   46.50569683872163,
   180.0,
   6.829999923706055,
   521.4000244140625,
   24.0,
   1043.27001953125,
   145.0,
   180.0,
   1777560703000.0,
   99.0,
   180.0,
   0.0,
   26.6299991607666]},
 {'metrics': [99.0,
   6.413110960274935,
   46.50582332164049,
   183.0,
   6.90500020980835,
   521.5999755859375,
   24.0,
   1064.0799560546875,
   146.0,
   183.0,
   1777560706000.0,
   99.0,
   183.0,
   0.20000000298023224,
   27.989999771118164]},
 {'metrics': [99.0,
   6.413313802331686,
   46.50595474988222,
   186.0,
   7.110000133514404,
   521.7999877929688,
   24.0,
   1085.3199462890625,
   146.0,
   186.0,
   1777560709000.0,
   99.0,
   186.0,
   0.20000000298023224,
   27.989999771118164]},
 {'metrics': [99.0,
   6.413527959957719,
   46.5060871001333,
   189.0,
   7.324999809265137,
   521.7999877929688,
   24.0,
   1107.5,
   147.0,
   189.0,
   1777560712000.0,
   99.0,
   189.0,
   0.0,
   28.5]},
 {'metrics': [99.0,
   6.413742620497942,
   46.506221294403076,
   192.0,
   7.53000020980835,
   521.4000244140625,
   24.0,
   1129.800048828125,
   147.0,
   192.0,
   1777560715000.0,
   99.0,
   192.0,
   -0.20000000298023224,
   28.5]},
 {'metrics': [98.0,
   6.413962142542005,
   46.506367307156324,
   195.0,
   7.855999946594238,
   521.2000122070312,
   24.0,
   1153.1099853515625,
   148.0,
   195.0,
   1777560718000.0,
   98.0,
   195.0,
   0.0,
   28.84000015258789]},
 {'metrics': [98.0,
   6.414185771718621,
   46.50651608593762,
   198.0,
   7.940000057220459,
   520.7999877929688,
   24.0,
   1177.0,
   147.0,
   198.0,
   1777560721000.0,
   98.0,
   198.0,
   -0.20000000298023224,
   28.280000686645508]},
 {'metrics': [98.0,
   6.414410909637809,
   46.50666519999504,
   201.0,
   7.940000057220459,
   520.4000244140625,
   24.0,
   1201.030029296875,
   146.0,
   201.0,
   1777560724000.0,
   98.0,
   201.0,
   -0.20000000298023224,
   28.280000686645508]},
 {'metrics': [98.0,
   6.4146277494728565,
   46.50681406259537,
   204.0,
   8.071000099182129,
   519.7999877929688,
   23.0,
   1224.4599609375,
   145.0,
   204.0,
   1777560727000.0,
   98.0,
   204.0,
   -0.20000000298023224,
   28.700000762939453]},
 {'metrics': [98.0,
   6.41484341584146,
   46.50698421522975,
   207.0,
   8.482000350952148,
   519.4000244140625,
   24.0,
   1249.5699462890625,
   144.0,
   207.0,
   1777560730000.0,
   98.0,
   207.0,
   -0.20000000298023224,
   28.969999313354492]},
 {'metrics': [98.0,
   6.415049862116575,
   46.507164845243096,
   210.0,
   8.668000221252441,
   519.0,
   23.0,
   1274.8699951171875,
   143.0,
   210.0,
   1777560733000.0,
   98.0,
   210.0,
   -0.20000000298023224,
   28.969999313354492]},
 {'metrics': [98.0,
   6.4152412209659815,
   46.507367603480816,
   213.0,
   8.920000076293945,
   518.4000244140625,
   23.0,
   1301.9200439453125,
   142.0,
   213.0,
   1777560736000.0,
   98.0,
   213.0,
   -0.20000000298023224,
   29.940000534057617]},
 {'metrics': [98.0,
   6.415396286174655,
   46.50759123265743,
   216.0,
   9.479999542236328,
   517.5999755859375,
   23.0,
   1329.43994140625,
   144.0,
   216.0,
   1777560739000.0,
   98.0,
   216.0,
   -0.20000000298023224,
   29.940000534057617]},
 {'metrics': [98.0,
   6.415541879832745,
   46.50783883407712,
   219.0,
   10.16100025177002,
   516.4000244140625,
   23.0,
   1358.97998046875,
   145.0,
   219.0,
   1777560742000.0,
   98.0,
   219.0,
   -0.4000000059604645,
   30.989999771118164]},
 {'metrics': [98.0,
   6.415661238133907,
   46.50810646824539,
   222.0,
   10.440999984741211,
   515.0,
   23.0,
   1390.260009765625,
   145.0,
   222.0,
   1777560745000.0,
   98.0,
   222.0,
   -0.4000000059604645,
   30.889999389648438]},
 {'metrics': [98.0,
   6.4157377649098635,
   46.50839296169579,
   225.0,
   10.758000373840332,
   513.4000244140625,
   23.0,
   1422.719970703125,
   144.0,
   225.0,
   1777560748000.0,
   98.0,
   225.0,
   -0.4000000059604645,
   30.889999389648438]},
 {'metrics': [98.0,
   6.415772549808025,
   46.50869303382933,
   228.0,
   11.225000381469727,
   512.2000122070312,
   23.0,
   1456.1600341796875,
   145.0,
   228.0,
   1777560751000.0,
   98.0,
   228.0,
   -0.4000000059604645,
   31.219999313354492]},
 {'metrics': [98.0,
   6.415762407705188,
   46.50900911539793,
   231.0,
   11.869000434875488,
   510.3999938964844,
   23.0,
   1491.4000244140625,
   145.0,
   231.0,